"""
core/monitor.py

Background monitor that watches all connected systems and generates
proactive alerts when something changes.

Instead of waiting for the user to ask, the monitor periodically
fetches snapshots from all available connectors, compares them
against history, and surfaces alerts when severity worsens or
new critical/warning findings appear.

This is the component that makes Savvy feel like it is actually
watching your systems 24/7, not just answering questions on demand.

Usage:
    from core.monitor import Monitor
    monitor = Monitor(registry, interval_seconds=300)
    monitor.start()
    alerts = monitor.get_alerts()
    monitor.stop()
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Callable, Optional

from core.history import SnapshotHistory, SnapshotDiff, snapshot_history
from core.registry import ConnectorRegistry, registry as default_registry
from core.schema import DiagnosticSnapshot, Severity


@dataclass
class Alert:
    """A proactive alert generated by the monitor."""
    id: str
    connector: str
    device_id: str
    severity: Severity
    title: str
    description: str
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    acknowledged: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "connector": self.connector,
            "device_id": self.device_id,
            "severity": self.severity.value,
            "title": self.title,
            "description": self.description,
            "generated_at": self.generated_at,
            "acknowledged": self.acknowledged,
        }


class Monitor:
    """
    Background monitor for all registered connectors.

    Runs a polling loop in a daemon thread. On each tick:
    1. Fetches a fresh snapshot from each available connector
    2. Stores it in history
    3. Computes diff against previous snapshot
    4. Generates alerts for severity changes and new critical findings
    """

    def __init__(
        self,
        registry: ConnectorRegistry = default_registry,
        history: SnapshotHistory = snapshot_history,
        interval_seconds: float = 300,
        on_alert: Optional[Callable[[Alert], None]] = None,
    ) -> None:
        self._registry = registry
        self._history = history
        self._interval = interval_seconds
        self._on_alert = on_alert
        self._alerts: list[Alert] = []
        self._lock = threading.Lock()
        self._thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._last_check: dict[str, str] = {}
        self._check_count: int = 0

    def start(self) -> None:
        """Start the background monitoring thread."""
        if self._thread and self._thread.is_alive():
            return
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._run,
            daemon=True,
            name="savvy-monitor",
        )
        self._thread.start()

    def stop(self) -> None:
        """Stop the background monitoring thread."""
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=10)

    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    def check_now(self) -> list[Alert]:
        """
        Run a single check cycle immediately (synchronous).
        Useful for testing and on-demand checks.
        """
        return self._check_all_connectors()

    def get_alerts(
        self,
        unacknowledged_only: bool = False,
        limit: int = 50,
    ) -> list[Alert]:
        """Return recent alerts, newest first."""
        with self._lock:
            alerts = list(reversed(self._alerts))
        if unacknowledged_only:
            alerts = [a for a in alerts if not a.acknowledged]
        return alerts[:limit]

    def acknowledge(self, alert_id: str) -> bool:
        """Mark an alert as acknowledged. Returns True if found."""
        with self._lock:
            for alert in self._alerts:
                if alert.id == alert_id:
                    alert.acknowledged = True
                    return True
        return False

    def acknowledge_all(self) -> int:
        """Acknowledge all pending alerts. Returns count acknowledged."""
        count = 0
        with self._lock:
            for alert in self._alerts:
                if not alert.acknowledged:
                    alert.acknowledged = True
                    count += 1
        return count

    def stats(self) -> dict:
        with self._lock:
            total = len(self._alerts)
            unacked = sum(1 for a in self._alerts if not a.acknowledged)
        return {
            "running": self.is_running(),
            "interval_seconds": self._interval,
            "check_count": self._check_count,
            "total_alerts": total,
            "unacknowledged_alerts": unacked,
            "last_check": self._last_check,
        }

    def _run(self) -> None:
        while not self._stop_event.is_set():
            self._check_all_connectors()
            self._stop_event.wait(timeout=self._interval)

    def _check_all_connectors(self) -> list[Alert]:
        new_alerts = []
        available = self._registry.available_names()

        for connector_name in available:
            try:
                spec = self._registry.get_spec(connector_name)
                if not spec:
                    continue
                connector = self._registry.get(connector_name)
                snapshot = connector.fetch(spec.default_device_id)
                diff = self._history.diff(snapshot)
                self._history.store(snapshot)
                self._last_check[connector_name] = datetime.now(
                    timezone.utc
                ).isoformat()

                if diff:
                    alerts = self._generate_alerts(snapshot, diff)
                    new_alerts.extend(alerts)
                    with self._lock:
                        self._alerts.extend(alerts)
                    if self._on_alert:
                        for alert in alerts:
                            try:
                                self._on_alert(alert)
                            except Exception:
                                pass

            except Exception:
                pass

        self._check_count += 1
        return new_alerts

    def _generate_alerts(
        self,
        snapshot: DiagnosticSnapshot,
        diff: SnapshotDiff,
    ) -> list[Alert]:
        alerts = []

        if diff.severity_worsened:
            alerts.append(Alert(
                id=f"{snapshot.source_connector}-severity-{int(time.time())}",
                connector=snapshot.source_connector,
                device_id=snapshot.device_id,
                severity=diff.current_severity,
                title=f"{snapshot.source_connector} severity worsened",
                description=(
                    f"Severity changed from {diff.previous_severity.value} "
                    f"to {diff.current_severity.value}. {diff.summary()}"
                ),
            ))

        for finding in diff.new_findings:
            if finding.severity in (Severity.CRITICAL, Severity.WARNING):
                alerts.append(Alert(
                    id=f"{snapshot.source_connector}-{finding.id}-{int(time.time())}",
                    connector=snapshot.source_connector,
                    device_id=snapshot.device_id,
                    severity=finding.severity,
                    title=f"New {finding.severity.value}: {finding.title}",
                    description=finding.description,
                ))

        return alerts
